// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS-_SxINoCPkqZsSGCMYX3EyyFdfS066g',
    appId: '1:384215534259:web:8bb6fcf7712ee310047ec6',
    messagingSenderId: '384215534259',
    projectId: 'taskiah-53c29',
    authDomain: 'taskiah-53c29.firebaseapp.com',
    storageBucket: 'taskiah-53c29.firebasestorage.app',
    measurementId: 'G-1SV1H0TZZT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQUwYHkiFQ2SEyCzG3kNrPxqZfch73_PY',
    appId: '1:384215534259:ios:483cdac28f583df1047ec6',
    messagingSenderId: '384215534259',
    projectId: 'taskiah-53c29',
    storageBucket: 'taskiah-53c29.firebasestorage.app',
    iosClientId: '384215534259-h1gres32281oqp2kbv3mtmjpqvp81dhj.apps.googleusercontent.com',
    iosBundleId: 'com.taskiah.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS-_SxINoCPkqZsSGCMYX3EyyFdfS066g',
    appId: '1:384215534259:web:030edb492475884c047ec6',
    messagingSenderId: '384215534259',
    projectId: 'taskiah-53c29',
    authDomain: 'taskiah-53c29.firebaseapp.com',
    storageBucket: 'taskiah-53c29.firebasestorage.app',
    measurementId: 'G-F2D24MKZ2R',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQUwYHkiFQ2SEyCzG3kNrPxqZfch73_PY',
    appId: '1:384215534259:ios:483cdac28f583df1047ec6',
    messagingSenderId: '384215534259',
    projectId: 'taskiah-53c29',
    storageBucket: 'taskiah-53c29.firebasestorage.app',
    iosClientId: '384215534259-h1gres32281oqp2kbv3mtmjpqvp81dhj.apps.googleusercontent.com',
    iosBundleId: 'com.taskiah.mobileApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA8ojvvB8_8wRQsk617RddZi7FPW2Iue4',
    appId: '1:384215534259:android:e4a15618e24797ef047ec6',
    messagingSenderId: '384215534259',
    projectId: 'taskiah-53c29',
    storageBucket: 'taskiah-53c29.firebasestorage.app',
  );

}